import type { AdminInfrastructureSnapshot } from './types'

export const adminInfrastructureDefaults: AdminInfrastructureSnapshot = {
  permissions: [
    { id: 'view_admin', label: 'צפייה בפאנל ניהול', description: 'גישה בסיסית למסכי הניהול.' },
    { id: 'view_users', label: 'צפייה במשתמשים', description: 'צפייה ברשימת משתמשים ופרטי הרשמה.' },
    { id: 'manage_users', label: 'ניהול משתמשים', description: 'אישור, חסימה, איפוס סיסמה ועדכון סטטוס.' },
    { id: 'manage_roles', label: 'ניהול הרשאות', description: 'עריכת תפקידים והרשאות.' },
    { id: 'manage_agencies', label: 'ניהול סוכנויות', description: 'יצירה ועדכון עסקים וסוכנויות.' },
    { id: 'manage_plans', label: 'ניהול תוכניות', description: 'יצירה ועריכת תוכניות שימוש.' },
    { id: 'manage_subscriptions', label: 'ניהול מנויים', description: 'עדכון מנוי, תקופת ניסיון וחסימות שימוש.' },
    { id: 'manage_landing_page', label: 'ניהול דף נחיתה', description: 'תשתית CMS לדף הנחיתה העתידי.' },
    { id: 'manage_templates', label: 'ניהול תבניות', description: 'תבניות סיכום, מיילים והמלצות.' },
    { id: 'upload_returns_files', label: 'העלאת קבצי תשואות', description: 'ניהול גרסאות קבצי רשות שוק ההון.' },
    { id: 'view_audit_logs', label: 'צפייה בלוג פעילות', description: 'צפייה בפעולות רגישות במערכת.' },
    { id: 'manage_system_settings', label: 'ניהול הגדרות מערכת', description: 'הגדרות גלובליות ו־Feature Flags.' },
    { id: 'manage_leads', label: 'ניהול לידים', description: 'ניהול CRM בסיסי ללידים ולקוחות.' },
    { id: 'manage_support', label: 'ניהול פניות תמיכה', description: 'טיפול בפניות, סטטוסים והערות פנימיות.' },
    { id: 'manage_email_templates', label: 'ניהול תבניות מייל', description: 'עריכת נוסחי מייל מערכת.' },
    { id: 'view_reports', label: 'צפייה בדוחות', description: 'דוחות שימוש, סטטיסטיקות ושגיאות מערכת.' },
  ],
  roles: [
    {
      id: 'super_admin',
      label: 'Super Admin',
      description: 'בעל המערכת עם גישה מלאה לכל פעולה.',
      permissions: [
        'view_admin',
        'view_users',
        'manage_users',
        'manage_roles',
        'manage_agencies',
        'manage_plans',
        'manage_subscriptions',
        'manage_landing_page',
        'manage_templates',
        'upload_returns_files',
        'view_audit_logs',
        'manage_system_settings',
        'manage_leads',
        'manage_support',
        'manage_email_templates',
        'view_reports',
      ],
    },
    {
      id: 'system_admin',
      label: 'System Admin',
      description: 'ניהול משתמשים, תוכן, תוכניות וקבצי מערכת.',
      permissions: ['view_admin', 'view_users', 'manage_users', 'manage_agencies', 'manage_plans', 'manage_subscriptions', 'manage_landing_page', 'manage_templates', 'upload_returns_files', 'view_audit_logs', 'manage_system_settings', 'manage_email_templates', 'view_reports'],
    },
    {
      id: 'business_manager',
      label: 'Business Manager',
      description: 'ניהול לידים, לקוחות ומנויים.',
      permissions: ['view_admin', 'view_users', 'manage_agencies', 'manage_subscriptions', 'manage_leads', 'view_reports'],
    },
    {
      id: 'support',
      label: 'Support',
      description: 'טיפול בפניות וצפייה מוגבלת במשתמשים.',
      permissions: ['view_admin', 'view_users', 'manage_support'],
    },
    {
      id: 'content_manager',
      label: 'Content Manager',
      description: 'ניהול תוכן, SEO, דף נחיתה ותבניות מייל.',
      permissions: ['view_admin', 'manage_landing_page', 'manage_templates', 'manage_email_templates'],
    },
    {
      id: 'agency_admin',
      label: 'מנהל סוכנות',
      description: 'ניהול משתמשים ולקוחות בתוך סוכנות אחת.',
      permissions: ['view_users', 'manage_users', 'manage_leads'],
    },
    {
      id: 'advisor',
      label: 'יועץ / סוכן',
      description: 'משתמש רגיל במערכת פגישה חכמה.',
      permissions: [],
    },
    {
      id: 'operations_user',
      label: 'תפעול',
      description: 'עובד תפעול בסוכנות.',
      permissions: ['view_users'],
    },
    {
      id: 'viewer',
      label: 'צפייה בלבד',
      description: 'גישה לקריאה בלבד לפי שיוך עתידי.',
      permissions: [],
    },
  ],
  plans: [
    {
      id: 'trial',
      name: 'ניסיון חינם',
      shortDescription: 'בדיקת מערכת לפני הפעלה מסחרית.',
      monthlyPrice: 0,
      annualPrice: 0,
      includedUsers: 1,
      monthlyMeetings: 10,
      clientLimit: 25,
      features: { pdfExport: true, excelExport: false, simulators: true, portfolioAnalysis: true, advancedTemplates: false, ai: false, extendedSupport: false, customBranding: false },
      status: 'active',
    },
    {
      id: 'basic',
      name: 'בסיסי',
      shortDescription: 'לעבודה עצמאית עם לקוחות ופגישות.',
      monthlyPrice: 149,
      annualPrice: 1490,
      includedUsers: 1,
      monthlyMeetings: 40,
      clientLimit: 150,
      features: { pdfExport: true, excelExport: true, simulators: true, portfolioAnalysis: true, advancedTemplates: false, ai: false, extendedSupport: false, customBranding: false },
      status: 'draft',
    },
    {
      id: 'professional',
      name: 'מקצועי',
      shortDescription: 'ליועצים פעילים עם תבניות, ייצוא ומיתוג.',
      monthlyPrice: 299,
      annualPrice: 2990,
      includedUsers: 3,
      monthlyMeetings: 120,
      clientLimit: 600,
      features: { pdfExport: true, excelExport: true, simulators: true, portfolioAnalysis: true, advancedTemplates: true, ai: false, extendedSupport: true, customBranding: true },
      status: 'draft',
    },
    {
      id: 'agency',
      name: 'סוכנות',
      shortDescription: 'ניהול צוות, לקוחות ותהליכים תחת סוכנות.',
      monthlyPrice: 799,
      annualPrice: 7990,
      includedUsers: 10,
      monthlyMeetings: 500,
      clientLimit: 2500,
      features: { pdfExport: true, excelExport: true, simulators: true, portfolioAnalysis: true, advancedTemplates: true, ai: false, extendedSupport: true, customBranding: true },
      status: 'draft',
    },
  ],
  registration: {
    registrationOpen: true,
    manualApprovalRequired: true,
    defaultTrialDays: 14,
    allowIndependentAdvisor: true,
    allowAgencyManager: true,
    allowAgencyEmployeeJoin: true,
    requireStrongPassword: true,
    requireTermsApproval: true,
    pendingApprovalMessage: 'הרשמתך התקבלה. לאחר בדיקה ואישור תישלח אליך הודעה למייל.',
  },
  landingPageDraft: {
    status: 'draft',
    title: 'מערכת פגישה חכמה ליועצים פיננסיים ופנסיוניים',
    metaDescription: 'פלטפורמה מקצועית לייבוא נתונים, ניתוח קופות, המלצות וסיכום פגישה.',
    slug: '/',
    canonicalUrl: '',
    openGraphImage: '',
    sections: [
      { id: 'hero', type: 'hero', title: 'ייעוץ פנסיוני מקצועי יותר. מהיר יותר.', text: 'סביבת עבודה אחת לייבוא נתונים, ניתוח תיק, סימולציות, המלצות וסיכום פגישה.', primaryButtonLabel: 'כניסה למערכת', primaryButtonHref: '/login', secondaryButtonLabel: 'בקשת הצטרפות', secondaryButtonHref: '/register', sortOrder: 1, active: true, desktopVisible: true, mobileVisible: true },
      { id: 'benefits', type: 'benefits', title: 'כל מה שצריך במקום אחד', text: 'ייבוא מסלקה והר הביטוח, טבלאות תשואות, תשתיות לקצבה וסיכום פגישה.', sortOrder: 2, active: true, desktopVisible: true, mobileVisible: true },
      { id: 'faq', type: 'faq', title: 'שאלות נפוצות', text: 'תשתית FAQ לעריכה מפאנל הניהול בהמשך.', sortOrder: 3, active: true, desktopVisible: true, mobileVisible: true },
      { id: 'contact', type: 'contact', title: 'השארת פרטים', text: 'כל ליד מהאתר ייכנס למודול הלידים בפאנל.', sortOrder: 4, active: true, desktopVisible: true, mobileVisible: true },
    ],
  },
  emailTemplates: [
    { id: 'registration_received', name: 'הרשמה התקבלה', subject: 'הרשמתך התקבלה', body: 'שלום {{client_name}}, הרשמתך התקבלה ונמצאת בבדיקה.', variables: ['client_name'], active: true },
    { id: 'user_approved', name: 'משתמש אושר', subject: 'חשבונך אושר', body: 'שלום {{client_name}}, החשבון שלך אושר וניתן להתחבר למערכת.', variables: ['client_name'], active: true },
    { id: 'password_reset', name: 'איפוס סיסמה', subject: 'איפוס סיסמה', body: 'שלום {{client_name}}, ניתן לאפס את הסיסמה בקישור שנשלח אליך.', variables: ['client_name'], active: true },
    { id: 'new_lead', name: 'ליד חדש', subject: 'ליד חדש מהאתר', body: 'נכנס ליד חדש: {{client_name}}, {{phone}}, {{email}}.', variables: ['client_name', 'phone', 'email'], active: true },
  ],
  dataImportKinds: [
    { id: 'gemel_returns', label: 'תשואות גמל', requiredColumns: ['שם קופה', 'יצרן', 'מספר קופה'], accepts: ['.xlsx', '.xls', '.csv', '.xml'] },
    { id: 'pension_returns', label: 'תשואות פנסיה', requiredColumns: ['שם קופה', 'יצרן', 'מספר קופה'], accepts: ['.xlsx', '.xls', '.csv', '.xml'] },
    { id: 'hishtalmut_returns', label: 'תשואות השתלמות', requiredColumns: ['שם קופה', 'יצרן', 'מספר קופה'], accepts: ['.xlsx', '.xls', '.csv', '.xml'] },
    { id: 'policy_returns', label: 'תשואות פוליסות', requiredColumns: ['שם קופה', 'יצרן', 'מספר קופה'], accepts: ['.xlsx', '.xls', '.csv', '.xml'] },
    { id: 'management_fees', label: 'דמי ניהול', requiredColumns: ['יצרן', 'סוג מוצר', 'דמי ניהול'], accepts: ['.xlsx', '.csv'] },
    { id: 'institution_codes', label: 'קודי מוסד', requiredColumns: ['יצרן', 'קוד מוסד'], accepts: ['.xlsx', '.csv'] },
    { id: 'investment_tracks', label: 'מסלולי השקעה', requiredColumns: ['יצרן', 'סוג מוצר', 'מסלול'], accepts: ['.xlsx', '.csv'] },
    { id: 'deposit_accounts', label: 'חשבונות להפקדה', requiredColumns: ['יצרן', 'סוג מוצר', 'חשבון'], accepts: ['.xlsx', '.csv'] },
    { id: 'service_centers', label: 'מוקדי שירות', requiredColumns: ['יצרן', 'טלפון'], accepts: ['.xlsx', '.csv'] },
    { id: 'agent_links', label: 'קישורי אזורי סוכן', requiredColumns: ['יצרן', 'קישור'], accepts: ['.xlsx', '.csv'] },
    { id: 'general_forms', label: 'טפסים כלליים', requiredColumns: ['שם טופס', 'קישור'], accepts: ['.xlsx', '.csv'] },
  ],
  auditActions: [
    { id: 'admin_login', label: 'כניסה לפאנל Admin', sensitive: true },
    { id: 'user_approved', label: 'אישור משתמש', sensitive: true },
    { id: 'user_blocked', label: 'חסימת משתמש', sensitive: true },
    { id: 'role_changed', label: 'שינוי תפקיד', sensitive: true },
    { id: 'permissions_changed', label: 'שינוי הרשאות', sensitive: true },
    { id: 'agency_changed', label: 'שינוי סוכנות', sensitive: true },
    { id: 'plan_changed', label: 'שינוי תוכנית', sensitive: true },
    { id: 'subscription_changed', label: 'שינוי מנוי', sensitive: true },
    { id: 'returns_file_uploaded', label: 'העלאת קובץ תשואות', sensitive: true },
    { id: 'template_changed', label: 'עריכת תבנית', sensitive: true },
    { id: 'landing_page_published', label: 'פרסום דף נחיתה', sensitive: true },
    { id: 'system_settings_changed', label: 'שינוי הגדרות מערכת', sensitive: true },
  ],
}
